[package]
name = "rc-node"
version.workspace = true
edition.workspace = true

[dependencies]
rc-types = { workspace = true }
rc-crypto = { workspace = true }
rc-store = { workspace = true }
rc-consensus = { workspace = true }
rc-state = { workspace = true }
rc-rpc = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_yaml = "0.9"
hex = "0.4"
reqwest = { version = "0.12", features = ["json"] }
